/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Vectors.c
**     Project     : ProcessorExpert
**     Processor   : MC9S08QG8CPB
**     Version     : Component 01.262, Driver 01.40, CPU db: 3.00.012
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2012-04-18, 17:50, # CodeGen: 34
**     Abstract    :
**         This component "MC9S08QG8_16" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
**     Settings    :
**
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#include "Cpu.h"
#include "SM1.h"
#include "FCONTROL.h"
#include "LATCH.h"
#include "ROTA.h"
#include "ROTB.h"
#include "ROTC.h"
#include "PWM1.h"
#include "TI1.h"
#include "I2C1.h"
#include "AD1.h"
#include "COP1.h"

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static void (* near const _vect[])(void) @0xFFD0 = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
         Cpu_Interrupt,                /* Int.no. 23 Vrti (at FFD0)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 22 VReserved22 (at FFD2)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 VReserved21 (at FFD4)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vacmp (at FFD6)                 Unassigned */
         AD1_Interrupt,                /* Int.no. 19 Vadc (at FFD8)                  Used */
         Cpu_Interrupt,                /* Int.no. 18 Vkeyboard (at FFDA)             Unassigned */
         I2C1_Interrupt,               /* Int.no. 17 Viic (at FFDC)                  Used */
         Cpu_Interrupt,                /* Int.no. 16 Vscitx (at FFDE)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vscirx (at FFE0)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Vscierr (at FFE2)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 Vspi (at FFE4)                  Unassigned */
         TI1_Interrupt,                /* Int.no. 12 Vmtim (at FFE6)                 Used */
         Cpu_Interrupt,                /* Int.no. 11 VReserved11 (at FFE8)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 VReserved10 (at FFEA)           Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 VReserved9 (at FFEC)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 VReserved8 (at FFEE)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 Vtpmovf (at FFF0)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 Vtpmch1 (at FFF2)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 Vtpmch0 (at FFF4)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  4 VReserved4 (at FFF6)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _EntryPoint                   /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

